import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
// import { ClerkProvider } from "@clerk/nextjs/dist/types/components.server";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  subsets:['latin'],
  weight: ["100","200","300","400", "500", "600", "700", "800", "900"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
